import HomeCarousel from "@/components/HomeCarousel";
import Introduction from "@/components/Introduction";
import Menu from "@/components/Menu";
import Information from "@/components/Information";

import Head from "next/head";
import Comments from "@/components/Comments";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mirror Public House | Gastro Pub </title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Mirror Public House Offical Web Site, generated by Kreatif Destek " />
        <meta name="author" content="Egecan Yildirim" />
        <meta name="keywords" content="Antalya Gastro Pub, Kaleici, Kaleici Pub " />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      </Head>
      <HomeCarousel />
      <Introduction />
      <Menu />
      <Information />
      <Comments />
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12764.939906786898!2d30.7061375!3d36.8847266!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14c3911b1a6e754f%3A0x17bf033b0b1bc00d!2sMirror%20Gastro%20%26%20Pub!5e0!3m2!1str!2str!4v1674652773842!5m2!1str!2str" style={{ width: '100%', height: 450, border: 0 }} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe>
      <Footer />
    </>
  )
}
